version: '3'
services:
  python_proxy:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    logging:
#      driver: json-file
      options:
        max-size: "10m"
        max-file: "10"
    volumes:
        - ./config.py:/home/tgproxy/config.py
        - ./mtprotoproxy.py:/home/tgproxy/mtprotoproxy.py
        - ./data:/home/tgproxy/data
        - /etc/localtime:/etc/localtime:ro
    ports:
      - "0.0.0.0:3443:3443"
